


import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Reseptor
 */
public class loginUser extends java.awt.Frame {
 Connection connection2 = null;
	ResultSet result2 = null;
	PreparedStatement prepared2 = null;
	Statement statiket2;
        
        
        private void koneksi2() {
	try{
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost/db_uas";
            String user="root";
            String pass=""; 
            connection2 = (Connection) DriverManager.getConnection(url,user,pass);
            statiket2 = (Statement) connection2.createStatement(result2.TYPE_SCROLL_SENSITIVE,result2.CONCUR_UPDATABLE);
            result2 = statiket2.executeQuery("select * from loginadmin");
       
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                System.exit(0);
            }
        
    }
        
	private void display2(){
        try{
            String sql2="select * from loginadmin";
            prepared2 = (PreparedStatement) connection2.prepareStatement(sql2);
            result2 = prepared2.executeQuery();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
 }
         private void Clear(){
        f_username.setText(null);
        f_pass.setText(null);
         }
         
    public loginUser() {
        initComponents();
        koneksi2();
        display2();
        
        
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        f_username = new javax.swing.JTextField();
        f_pass = new javax.swing.JPasswordField();
        btn_exit = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        f_no = new javax.swing.JTextField();
        f_nama = new javax.swing.JTextField();

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Reseptor\\Downloads\\pngwing.com.png")); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Reseptor\\Downloads\\Untitled design (3).png")); // NOI18N

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG DI PEMBELIAN TIKET");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 394, 18));

        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 20));

        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        f_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(f_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 141, 20));
        jPanel1.add(f_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 141, -1));

        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 85, -1));

        btn_next.setText("Next");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        jPanel1.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 87, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SUMEDANG AIRPORT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 394, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Reseptor\\Downloads\\Untitled_design__2_-removebg-preview.png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 90, 120));

        jLabel3.setText("NO WA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));
        jPanel1.add(f_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 140, -1));
        jPanel1.add(f_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 140, -1));

        add(jPanel1, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
              System.exit(0);

    }//GEN-LAST:event_btn_exitActionPerformed

    private void f_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_usernameActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
  try{
            koneksi2();
            statiket2 = (Statement) connection2.createStatement();
            String SQL1 = "insert into loginadmin values('"+f_username.getText()+"','"+f_no.getText()+"','"+f_nama.getText()+"','"+f_pass.getText()+"')";
            statiket2.executeUpdate(SQL1);
            display2();
            statiket2.close();
            connection2.close();
            Clear();
            JOptionPane.showMessageDialog(null, "berhasil simpan");
            
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
        new formUser().setVisible(true);
                dispose();
  
  
    }//GEN-LAST:event_btn_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
                    new loginUser().setVisible(true);
                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_next;
    private javax.swing.JTextField f_nama;
    private javax.swing.JTextField f_no;
    private javax.swing.JPasswordField f_pass;
    private javax.swing.JTextField f_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
